### PR TITLE
WIP on GHC 9.2 support

### PR DESCRIPTION
**Pull request by alanz**
Slash and burn approach, strip it down to GHC 9.2 only, comment out
stuff to get it to compile, build it back up again.

Hopefully the tests are solid

Ref https://github.com/facebookincubator/retrie/issues/36

### CODE REVIEW

**Comment by pepeiborra** [comment]
Ping me when this is ready for review

**Comment by alanz** [comment]
> Ping me when this is ready for review

Because retrie uses SYB for making changes, a change happens in an isolated context where a match occurs, with no access to surrounding context in the change function. Which means the surrounding context must be in the delta form to ensure the replacement works properly.

This means I need to re-introduce the equivalent of the delta phase into the new ghc-exactprint. I am not sure how long this will take, but am starting on it.

**Comment by alanz** [comment]
@pepeiborra I stopped working on this because @xich said he was going to take it further.  Not sure how far he has got though.

**Comment by pepeiborra** [comment]
This is blocking the HLS support for 9.2, so I am keen on unblocking it. We can upload an "early" version to Hackage and improve it later.

I have fixed the build, added TODOs for the tests, bumped the version number and updated the changelog. Planning to upload to Hackage as soon as tonight. If you have any reservations @alanz or @xich let me know ASAP

**Comment by alanz** [comment]
I have no reservations

**Comment by pepeiborra** [comment]
> > Ping me when this is ready for review
> 
> Because retrie uses SYB for making changes, a change happens in an isolated context where a match occurs, with no access to surrounding context in the change function. Which means the surrounding context must be in the delta form to ensure the replacement works properly.
> 
> This means I need to re-introduce the equivalent of the delta phase into the new ghc-exactprint. I am not sure how long this will take, but am starting on it.

What was the outcome of this @alanz ? ghcide uses the same SYB approach, and I'm struggling to figure out how to convert absolute positions to delta form

**Comment by alanz** [comment]
@pepeiborra There is now [makeDeltaAst](https://hackage.haskell.org/package/ghc-exactprint-1.3.0/docs/Language-Haskell-GHC-ExactPrint.html#v:makeDeltaAst) which does this

**Pull request merged**
